{"frames":[{"func":"funMergeMRlt(models_to_merge, modelPath, modelversion)","file":"","line_number":2,"end_line_number":2,"character_number":3,"end_character_number":56},{"func":"readRDS(file.path(paste0(getwd(), \"/\", path, \"/rlt/\", rltfilename[1])))","file":"","line_number":9,"end_line_number":9,"character_number":3,"end_character_number":88},{"func":"gzfile(file, \"rb\")","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error in gzfile(file, \"rb\") : cannot open the connection\n"}